# Dockerfile to run pgadmin
FROM dpage/pgadmin4

ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=root

EXPOSE 80

#  image: dpage/pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=root
#     ports:
#       - "8085:80"
#     volumes:
#       - "./pgadmin_data:/var/lib/pgadmin"
#     depends_on:
#       ny-taxi-data:
#         condition: service_started