version: 2

sources:
  - name: staging
    database: phillycrime
    schema: philly_crime_db

  
    tables:
      - name: income
      - name: phillycrimes
      - name: playground
      - name: weather